@baseUrl = http://localhost:4000
@videoId = d9d0d8d6-037c-49f7-b884-f619046fc07c

### =========================
### LISTAR VIDEOS
### =========================
GET {{baseUrl}}/videos
Accept: application/json


### =========================
### SCAN DE LIBRERÍA
### =========================
GET {{baseUrl}}/videos/scanVideos
Accept: application/json


### =========================
### OBTENER VIDEO POR ID
### =========================
GET {{baseUrl}}/videos/{{videoId}}
Accept: application/json


### =========================
### STREAM DE VIDEO
### =========================
GET {{baseUrl}}/videos/{{videoId}}/stream


### =========================
### PATCH VIDEO (metadata básica)
### =========================
PATCH {{baseUrl}}/videos/{{videoId}}
Content-Type: application/json

{
  "title": "Nuevo título de prueba",
  "description": "Descripción editada manualmente",
  "providerUrl": "https://example.com"
}
